#! /bin/bash

# 
#            --------------------------------------------------
#                            Ehtools Framework          
#            --------------------------------------------------
#        Copyright (C) <2015>  <Entynetproject (Ivan Nikolsky)>
#
#        This program is free software: you can redistribute it and/or modify
#        it under the terms of the GNU General Public License as published by
#        the Free Software Foundation, either version 3 of the License, or
#        any later version.
#
#        This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#
#        You should have received a copy of the GNU General Public License
#        along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
#
#    Ehtools framework [based on lscript]
#    
#    
#    About Author :
#    
#    Founder : Entynetproject (Ivan Nikolsky)
#    Instagram : @entynetproject | @ehtools_framework
#    Email : entynetproject@gmail.com
#    Project's site : https://entynethacker.wixsite.com/ehtools
#    Entynetproject's site : http://entynetproject.simplesite.com/
#
#! /bin/bash
clear
printf '\033]2;ehtools INSTALLER\a'

echo -e "                                                           "
echo -e "███████╗██╗  ██╗████████╗ ██████╗  ██████╗ ██╗     ███████╗ \e[1;33mv2.1.6\e[0m"
echo -e "██╔════╝██║  ██║╚══██╔══╝██╔═══██╗██╔═══██╗██║     ██╔════╝"
echo -e "█████╗  ███████║   ██║   ██║   ██║██║   ██║██║     ███████╗"
echo -e "██╔══╝  ██╔══██║   ██║   ██║   ██║██║   ██║██║     ╚════██║"
echo -e "███████╗██║  ██║   ██║   ╚██████╔╝╚██████╔╝███████╗███████║"
echo -e "╚══════╝╚═╝  ╚═╝   ╚═╝    ╚═════╝  ╚═════╝ ╚══════╝╚══════╝"
echo -e "\e[1;33mBy Entynetproject corp\e[0m"
sleep 3
echo -e "More on our site:"
sleep 3
echo -e "==> \e[1;33mhttps://entynethacker.wixsite.com/ehtools\e[0m"                                                           
sleep 3
echo -e "==> \e[1;33mhttp://entynetproject.simplesite.com/\e[0m"
sleep 3
echo -e "Creators of Ehtools Framework:"
sleep 3
echo -e "\e[4;34mIvan Nikolsky (Enty)\e[0m - Main Coder"
sleep 3
echo -e "\e[4;33mDJ Mobley\e[0m - Ascii Designer"
sleep 3
echo -e "\e[4;32mEgor Egorich\e[0m - Color Designer"
sleep 3
echo -e "Press \e[1;33many key\e[0m to install ehtools"
read -n 1
clear
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
if [[ "$DIR" != "/bin" ]]
then
	echo -e "\e[44mSetting up ehtools certs...\e[0m"
        sleep 20
        echo -e "\e[4;31m/root/ehtools/eht1 returned an error code (/bin/euh not found!) "segmentation fault!"\e[0m"
        echo -e "\e[4;31m/root/ehtools/eht1 returned an error code (/bin/euh not found!) "segmentation fault!"\e[0m"
	sleep 4
        echo -e "\e[4;31m/bin/euh returned fatal error\e[0m"
	sleep 4
        echo -e "\e[1;34mReloading...\e[0m"
        sleep 1
        echo -e "\e[1;34mSetting up ehtools certs...\e[0m"
        sleep 2
        echo -e "\e[44mConnecting to server...\e[0m"
        sleep 10
        echo -e "\e[4;31m141.152.251.19: connection refused! server not found!\e[0m"
        sleep 3
        echo -e "\e[4;31m/bin/euh returned fatal error\e[0m"
        echo -e "\e[4;31m/bin/euh returned fatal error\e[0m"
        echo -e "\e[4;31m/bin/euh returned fatal error\e[0m"
        echo -e "\e[4;31m/bin/euh returned fatal error\e[0m"
	sleep 3
        echo -e "\e[1;34mReloading...\e[0m"
        sleep 4
        echo -e "\e[4;31m/bin/euh returned fatal error!\e[0m"
        echo -e "\e[4;31m/bin/euh returned fatal error!\e[0m"
        sleep 3
        echo -e "\e[1;34mReloading...\e[0m"
        sleep 10
        echo -e "\e[1;34mSetting up ehtools certs...\e[0m"
        sleep 30
        echo -e "\e[4;31m/bin/euh returned fatal error!\e[0m"
        echo -e "\e[4;31m/bin/euh returned fatal error!\e[0m"
        sleep 3
        echo -e "\e[1;34mReloading...\e[0m"
        sleep 20
        echo -e "\e[4;31m/bin/euh returned fatal error!\e[0m"
        sleep 3
        echo -e "\e[1;34mReloading...\e[0m"
        sleep 10
        echo -e "\e[4;31m/bin/euh returned fatal error!\e[0m"
        echo -e "\e[4;31m/bin/euh returned fatal error!\e[0m"
	sleep 3
	echo -e "\e[101m\e[1;77m/root/ehtools/eht1 returned an error code (101)\e[0m"
	sleep 4
	echo -e "\e[101m\e[1;77m/bin/euh returned fatal error!\e[0m"
        sleep 4
        echo -e "\e[101m\e[1;77m/root/ehtools/eht1 returned an error code (319)\e[0m"
        sleep 4
        echo -e "\e[1;34mReloading...\e[0m"
        sleep 20
	echo -e "\e[4;31m/bin/euh returned fatal error\e[0m"
	sleep 3
        echo -e "\e[1;34mReloading...\e[0m"
	if [[ -d /bin ]]
	then
		rm /root/ehtools/euh
	fi
	mkdir /root/euh
	cp -r "$DIR"/* /root/euh
	gnome-terminal -- "bash /bin/euh"
fi

sleep 3
echo -e "chmod +x /root/ehtools/eht1" 
echo -e "chmod +x /root/ehtools/eht1"
echo -e "chmod +x /root/ehtools/eht1" 
echo -e "chmod +x /root/ehtools/eht1" 
echo -e "chmod +x /root/ehtools/eht1"
echo -e "chmod +x /root/ehtools/eht1"
echo -e "chmod +x /root/ehtools/eht1"
echo -e "chmod +x /root/ehtools/eht1"
sleep 5
echo -e "\e[44mOK...\e[0m"
sleep 10
echo -e "\e[4;32mSuccess!\e[0m"
sleep 3
chmod +x /root/ehtools/eht1
chmod +x /root/ehtools/eht2
chmod +x /root/ehtools/eht3
chmod +x /root/ehtools/eht21
chmod +x /root/ehtools/eht31
chmod +x /root/ehtools/ehtools
chmod +x /root/ehtools/eht4
chmod +x /root/ehtools/eht41
chmod +x /root/ehtools/eht42
chmod +x /root/ehtools/eht43
chmod +x /root/ehtools/ls/l131.sh
chmod +x /root/ehtools/ls/l132.sh
chmod +x /root/ehtools/ls/l133.sh
chmod +x /root/ehtools/uninstall.sh
chmod +x /root/ehtools/euh
clear
echo -e "Copying script to /bin/ehtools"
sleep 1
mkdir /bin/ehtools
cd /root/ehtools
cp /root/ehtools/ehtools /bin/ehtools
cp /root/ehtools/eht1 /bin/ehtools
cp /root/ehtools/eht2 /bin/ehtools
cp /root/ehtools/eht3 /bin/ehtools
cp /root/ehtools/eht31 /bin/ehtools
cp /root/ehtools/eht4 /bin/ehtools
cp /root/ehtools/eht41 /bin/ehtools
cp /root/ehtools/eht42 /bin/ehtools
cp /root/ehtools/eht43 /bin/ehtools
cp /root/ehtools/euh /bin
chmod +x /bin/euh
cp /root/ehtools/eht1 /bin
chmod +x /bin/eht1
cp /root/ehtools/eht2 /bin
chmod +x /bin/eht2
cp /root/ehtools/eht3 /bin
chmod +x /bin/eht3
cp /root/ehtools/eht31 /bin
chmod +x /bin/eht31
cp /root/ehtools/eht4 /bin
chmod +x /bin/eht4
cp /root/ehtools/eht41 /bin
chmod +x /bin/eht41
cp /root/ehtools/eht42 /bin
chmod +x /bin/eht42
cp /root/ehtools/eht43 /bin
chmod +x /bin/eht43
cp /root/ehtools/eht21 /bin
chmod +x /bin/eht21
clear
