#! /bin/bash

# 
#            --------------------------------------------------
#                            Ehtools Framework          
#            --------------------------------------------------
#        Copyright (C) <2015>  <Entynetproject (Ivan Nikolsky)>
#
#        This program is free software: you can redistribute it and/or modify
#        it under the terms of the GNU General Public License as published by
#        the Free Software Foundation, either version 3 of the License, or
#        any later version.
#
#        This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#
#        You should have received a copy of the GNU General Public License
#        along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
#
#    Ehtools framework [based on lscript]
#    
#    
#    About Author :
#    
#    Founder : Entynetproject (Ivan Nikolsky)
#    Instagram : @entynetproject | @ehtools_framework
#    Email : entynetproject@gmail.com
#    Project's site : https://entynethacker.wixsite.com/ehtools
#    Entynetproject's site : http://entynetproject.simplesite.com/
#



function update_ehtools
{
	echo -e "Checking for updates..."
	TESTINTERNETCONNECTION=$(curl -s checkip.dyndns.org | sed -e 's/.*Current IP Address: //' -e 's/<.*$//')
	if [[ "$TESTINTERNETCONNECTION" != "" ]]
	then
		VER=$(timeout -s SIGTERM 20 curl "https://raw.githubusercontent.com/entynetproject/ehtools/master/version.txt" 2>/dev/null)
		if [[ "$VERSION" != "$VER" ]]
		then
			clear
			echo -e "There is an update available."
			echo -e "Current version: $VERSION"
			echo -e "Updated version: $VER"
			echo -e "$PAKTC"
			$READAK
			clear
			echo -e "Do you want to update?"$YNONLY": "
			read UPDATEYN
			if [[ "$UPDATEYN" = "y" ]]
			then
				clear
				#~ echo -e "Making new directory for the old ehtools (will pass it to /root/ehtold)"
				sleep 1
				if [[ -d /root/ehtold ]]
				then
					rm -r /root/ehtold
				fi
				mkdir /root/ehtold
				echo -e ""
				#~ echo -e "Moving ehtools to ehtold"
				sleep 1
				mv "$EPATH" /root/ehtold
				#~ echo -e "Cloning the latest github version to new "$EPATH""
				sleep 1
				cd
				git clone https://github.com/entynetproject/ehtools.git
				cd "$EPATH"
				chmod +x install.sh
				clear
				sleep 1
				if [[ -f /root/ehtold/ehtools/IAGREE.txt ]]
				then
					cp /root/ehtold/ehtools/IAGREE.txt "$EPATH"
				fi
				if [[ -d /root/ehtold/ehtools/ks ]]
				then
					echo -e "Copying your shortcuts"
					cp -r /root/ehtold/ehtools/ks "$EPATH"
					echo -e "Done."
					sleep 0.2
				fi
				if [[ -d /root/ehtold/ehtools/settings ]]
				then
					echo -e "Copying your settings"
					cp -r /root/ehtold/ehtools/settings "$EPATH"
					echo -e "Done."
					sleep 0.2
				fi
				if [[ -f /root/ehtold/ehtools/wlanmon.txt ]]
				then
					echo -e "Copying your interfaces"
					cp /root/ehtold/ehtools/wlanmon.txt "$EPATH"
					echo -e "Done."
					sleep 0.2
				fi
				echo -e ""
				if [[ -f /root/ehtold/ehtools/wlan.txt ]]
				then
					cp /root/ehtold/ehtools/wlan.txt "$EPATH"
					echo -e "Done."
					sleep 0.2
					clear
				fi
				echo -e "$PAKTC"
				$READAK
				cd "$EPATH"
				gnome-terminal -e ./install.sh
				clear 
				sleep 1
				rm -rf /root/ehtold
				echo -e "Exiting..."
				sleep 1
				kill -9 $PPID
			else 
				clear
				echo -e "You didnt select "y" so you go back..."
				sleep 3
				exec bash "$0"
			fi
		else
			echo -e "There is no update available"
			sleep 1
			echo -e "Installed version: $VERSION"
			sleep 1
			echo -e "Github version:    $VER"
			sleep 1
			echo -e "$PAKTGB"
			$READAK	
			exec bash "$0"
		fi
	else
		clear
		echo -e "There is no connection."
		sleep 1
		echo -e "Maybe you should type 'stop' in the main menu to gain internet access again"
		echo -e ""
		echo -e "$PAKTGB"
		$READAK
		exec bash "$0"
	fi	
}
