#!/bin/bash

#            --------------------------------------------------
#                            Ehtools Libraries          
#            --------------------------------------------------
#                  Copyright (C) <2019>  <Entynetproject>
#
#        This program is free software: you can redistribute it and/or modify
#        it under the terms of the GNU General Public License as published by
#        the Free Software Foundation, either version 3 of the License, or
#        any later version.
#
#        This program is distributed in the hope that it will be useful,
#        but WITHOUT ANY WARRANTY; without even the implied warranty of
#        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#        GNU General Public License for more details.
#
#        You should have received a copy of the GNU General Public License
#        along with this program.  If not, see <http://www.gnu.org/licenses/>.

CE="\033[0m"
RS="\033[1;31m"
YS="\033[1;33m"

if [[ $EUID -ne 0 ]]
then
   sleep 1
   echo -e "["$RS"*"$CE"] "$RS"This script must be run as "$YS"root"$RS"!"$CE"" 1>&2
   sleep 1
   exit
fi

{
chattr +i /bin/ehtools/ehtools
chattr +i /bin/ehtools/ehtconsole
chattr +i /bin/ehtools/epasswd
chattr +i /bin/ehtools/ehtkey
chattr +i /bin/ehtools/ehtmod
chattr +i /bin/ehtools/ehtapp
chattr +i /bin/ehtools/uiecache
chattr +i /etc/ehtools/login
chattr +i /etc/ehtools/password
chattr +i /etc/ehtools
chattr +i /etc/ehtools/root
chattr +i /etc/ehtools/root/password
} &> /dev/null
