#! /bin/bash

# 
#            --------------------------------------------------
#                            Ehtools Libraries          
#            --------------------------------------------------
#          Copyright (C) <2015>  <Entynetproject (Ivan Nikolsky)>
#
#        This program is free software: you can redistribute it and/or modify
#        it under the terms of the GNU General Public License as published by
#        the Free Software Foundation, either version 3 of the License, or
#        any later version.
#
#        This program is distributed in the hope that it will be useful,
#        but WITHOUT ANY WARRANTY; without even the implied warranty of
#        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#        GNU General Public License for more details.
#
#        You should have received a copy of the GNU General Public License
#        along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
#    About Author :   
#    Founder   : Entynetproject (Ivan Nikolsky)
#    Site      : http://entynetproject.simplesite.com/
#    Instagram : @entynetproject 
#    Twitter   : @entynetproject
#    Email     : entynetproject@gmail.com
#

CE="\e[0m"
RS="\e[1;31m"
YS="\e[1;33m"

if [[ $EUID -ne 0 ]]
then
   echo "["$RS"*"$CE"] "$RS"This script must be run as "$YS"root"$CE"" 1>&2
   exit
fi

{
CONF="$( cat /root/ehtools/etc/.config )"
chattr -i /etc/ehtools
chattr -i /etc/ehtools/login
mkdir /etc/ehtools/.dec
mv /etc/ehtools/login /etc/ehtools/.dec
openssl enc -aes-256-cbc -base64 -pass pass:"$CONF" -d -p -in /etc/ehtools/.dec/login -out /etc/ehtools/login
chattr +i /etc/ehtools/login
chattr -i /etc/ehtools/password
mv /etc/ehtools/password /etc/ehtools/.dec
openssl enc -aes-256-cbc -base64 -pass pass:"$CONF" -d -p -in /etc/ehtools/.dec/password -out /etc/ehtools/password
chattr +i /etc/ehtools/password
chattr -i /etc/ehtools/root
chattr -i /etc/ehtools/root/password
mkdir /etc/ehtools/root/.dec
mv /etc/ehtools/root/password /etc/ehtools/root/.dec
openssl enc -aes-256-cbc -base64 -pass pass:"$CONF" -d -p -in /etc/ehtools/root/.dec/password -out /etc/ehtools/root/password
chattr +i /etc/ehtools/root/password
rm -r /etc/ehtools/root/.dec
chattr +i /etc/ehtools/root
rm -r /etc/ehtools/.dec
chattr +i /etc/ehtools
} &> /dev/null
