#!/bin/bash

#            --------------------------------------------------
#                            Ehtools Framework          
#            --------------------------------------------------
#                  Copyright (C) <2015>  <Entynetproject>   
#
#        This program is free software: you can redistribute it and/or modify
#        it under the terms of the GNU General Public License as published by
#        the Free Software Foundation, either version 3 of the License, or
#        any later version.
#
#        This program is distributed in the hope that it will be useful,
#        but WITHOUT ANY WARRANTY; without even the implied warranty of
#        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#        GNU General Public License for more details.
#
#        You should have received a copy of the GNU General Public License
#        along with this program.  If not, see <http://www.gnu.org/licenses/>.

CE="\033[0m"
RS="\033[1;31m"
YS="\033[1;33m"

if [[ $EUID -ne 0 ]]
then
   sleep 1
   echo -e "["$RS"*"$CE"] "$RS"This script must be run as "$YS"root"$RS"!"$CE"" 1>&2
   sleep 1
   exit
fi

passcode="$(cat /root/ehtools/etc/.config)"
read -s -p $'Password: ' output
if [[ $output != $passcode ]]
then
	echo -e "libenc: Sorry"
else
{
CONF="$( cat /root/ehtools/etc/.config )"
cd /etc/ehtools
chattr -i /etc/ehtools
chattr -i /etc/ehtools/login
openssl enc -aes-256-cbc -pass pass:"$CONF" -p -in login -out login.enc -base64
rm login
mv login.enc login
chattr +i /etc/ehtools/login
chattr -i /etc/ehtools/password
openssl enc -aes-256-cbc -pass pass:"$CONF" -p -in password -out password.enc -base64
rm password
mv password.enc password
chattr +i /etc/ehtools/password
chattr -i /etc/ehtools/root
chattr -i /etc/ehtools/root/password
cd /etc/ehtools/root
openssl enc -aes-256-cbc -pass pass:"$CONF" -p -in password -out password.enc -base64
rm password
mv password.enc password
chattr +i /etc/ehtools/root/password
chattr +i /etc/ehtools/root
chattr +i /etc/ehtools
} &> /dev/null
fi
