#!/bin/bash

CE="\e[0m"
RS="\e[1;31m"
YS="\e[1;33m"

printf '\033]2;activate ehtools\a'

ACTKEY="$( curl "https://raw.githubusercontent.com/entynetproject/ECLI/master/hello.txt" 2>/dev/null )"
sleep 1
echo -e "Enter your ehtools activation key!"
echo -e "Or buy it on ehtools site!"
read -p $'(\e[4;93mactivation_key\e[0m\en)> ' KEYACT
sleep 1
if [[ "$KEYACT" != "$ACTKEY" ]]
then
sleep 1
echo -e "["$RS"*"$CE"] "$RS"Failed to activate ehtools, try again later!"$CE""
sleep 8
exit
fi

r=$(( RANDOM%7999+1001));
s=$(( RANDOM%7999+1001)); 
h=$(( RANDOM% 7999+1001)); 
g=$(( RANDOM% 7999+1001)); 

{
rm -r /etc/ehtools
} &> /dev/null

mkdir /etc/ehtools
mkdir /etc/ehtools/root
mkdir /etc/ehtools/root/service
mkdir /etc/ehtools/root/service/late
echo "$r-$s-$h-$g" >> /etc/ehtools/root/service/late/ehtkey.txt
echo "$ACTKEY" >> /etc/ehtools/root/service/ehtkey.txt
sleep 3
