#! /bin/bash

# 
#            --------------------------------------------------
#                            Ehtools Libraries          
#            --------------------------------------------------
#          Copyright (C) <2015>  <Entynetproject (Ivan Nikolsky)>
#
#        This program is free software: you can redistribute it and/or modify
#        it under the terms of the GNU General Public License as published by
#        the Free Software Foundation, either version 3 of the License, or
#        any later version.
#
#        This program is distributed in the hope that it will be useful,
#        but WITHOUT ANY WARRANTY; without even the implied warranty of
#        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#        GNU General Public License for more details.
#
#        You should have received a copy of the GNU General Public License
#        along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
#    About Author :   
#    Founder   : Entynetproject (Ivan Nikolsky)
#    Site      : http://entynetproject.simplesite.com/
#    Instagram : @entynetproject 
#    Twitter   : @entynetproject
#    Email     : entynetproject@gmail.com
#

CE="\e[0m"
RS="\e[1;31m"
YS="\e[1;33m"

printf '\033]2;activate ehtools\a'

ACTKEY="$( curl "https://raw.githubusercontent.com/entynetproject/ECLI/master/hello.txt" 2>/dev/null )"
sleep 1
echo -e "Enter your ehtools activation key!"
echo -e "Or buy it on ehtools site!"
read -p $'(\e[4;93mactivation_key\e[0m\en)> ' KEYACT
sleep 1
if [[ "$KEYACT" != "$ACTKEY" ]]
then
sleep 1
echo -e "["$RS"*"$CE"] "$RS"Failed to activate ehtools, try again later!"$CE""
sleep 8
exit
fi

r=$(( RANDOM%7999+1001));
s=$(( RANDOM%7999+1001)); 
h=$(( RANDOM% 7999+1001)); 
g=$(( RANDOM% 7999+1001)); 

{
chattr -i /etc/ehtools/root/service
chattr -i /etc/ehtools/root/service/late
chattr -i /etc/ehtools/root/service/ehtkey.txt
chattr -i /etc/ehtools/root/service/late/ehtkey.txt
rm -r /etc/ehtools
} &> /dev/null

mkdir /etc/ehtools
mkdir /etc/ehtools/root
mkdir /etc/ehtools/root/service
mkdir /etc/ehtools/root/service/late
echo "$r-$s-$h-$g" >> /etc/ehtools/root/service/late/ehtkey.txt
{
chattr -i /tmp/config
chattr -i /tmp/config/config.txt
chattr -i /tmp/config/configure.txt
} &> /dev/null
rm /tmp/config/config.txt
rm /tmp/config/configure.txt
cat /etc/ehtools/root/service/late/ehtkey.txt >> /tmp/config/configure.txt
cat /etc/ehtools/root/service/late/ehtkey.txt >> /tmp/config/config.txt
{
chattr +i /tmp/config
chattr +i /tmp/config/config.txt
chattr +i /tmp/config/configure.txt
} &> /dev/null
echo "$ACTKEY" >> /etc/ehtools/root/service/ehtkey.txt
sleep 3

{
chattr +i /etc/ehtools/root/service
chattr +i /etc/ehtools/root/service/late
chattr +i /etc/ehtools/root/service/ehtkey.txt
chattr +i /etc/ehtools/root/service/late/ehtkey.txt
} &> /dev/null
