#! /bin/bash

# 
#            --------------------------------------------------
#                            Ehtools Libraries          
#            --------------------------------------------------
#          Copyright (C) <2015>  <Entynetproject (Ivan Nikolsky)>
#
#        This program is free software: you can redistribute it and/or modify
#        it under the terms of the GNU General Public License as published by
#        the Free Software Foundation, either version 3 of the License, or
#        any later version.
#
#        This program is distributed in the hope that it will be useful,
#        but WITHOUT ANY WARRANTY; without even the implied warranty of
#        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#        GNU General Public License for more details.
#
#        You should have received a copy of the GNU General Public License
#        along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
#    About Author :   
#    Founder   : Entynetproject (Ivan Nikolsky)
#    Site      : http://entynetproject.simplesite.com/
#    Instagram : @entynetproject 
#    Twitter   : @entynetproject
#    Email     : entynetproject@gmail.com
#

{
chattr +i /bin/ehtools/ehtools
chattr +i /bin/ehtools/ehtconsole
chattr +i /etc/ehtools/login
chattr +i /etc/ehtools/password
chattr +i /etc/ehtools
chattr +i /etc/ehtools/root
chattr +i /etc/ehtools/root/password
} &> /dev/null
