#!/bin/bash

CE="\e[0m"
RS="\e[1;31m"
YS="\e[1;33m"

{
ASESR="$( timeout -s SIGTERM 3 curl -s checkip.dyndns.org | sed -e 's/.*Current IP Address: //' -e 's/<.*$//' )"
KEYEK="$( cat /etc/ehtools/root/service/ehtkey.txt )"
} &> /dev/null

if [[ "$ASESR" != "" ]]
then 

KEYKE="$( timeout -s SIGTERM 3 curl "https://raw.githubusercontent.com/entynetproject/ECLI/master/hello.txt" 2>/dev/null )"

if [[ "$KEYEK" != "$KEYKE" ]]
then

sleep 1
echo -e "["$RS"*"$CE"] "$RS"Failed to open session for libconf!"$CE""
sleep 1
echo -e "("$YS"it's may be caused by the fact that you have not bought ehtools or by bad internet connection!"$CE")"
sleep 1
exit

fi

else
sleep 1
echo -e "["$RS"*"$CE"] "$RS"There is no connection!"$CE""
sleep 1
exit
fi

{
chattr +i /etc/ehtools/config
chattr +i /etc/ehtools
} &> /dev/null
