#!/bin/bash

{
KEYEK="$( cat /etc/ehtools/root/service/ehtkey.txt )"
KEYKE="$( curl "https://raw.githubusercontent.com/entynetproject/ECLI/master/hello.txt" 2>/dev/null )"
} &> /dev/null

if [[ "$KEYEK" != "$KEYKE" ]]
then

sleep 1
echo -e "["$RS"*"$CE"] "$RS"Failed to open session for libchattr, did you buy ehtools?"$CE""
sleep 1
exit

fi

{
chattr +i /bin/ehtools/ehtools
chattr +i /bin/ehtools/ehtconsole
chattr +i /etc/ehtools/login
chattr +i /etc/ehtools/password
chattr +i /etc/ehtools
chattr +i /etc/ehtools/root
chattr +i /etc/ehtools/root/password
} &> /dev/null
